### ISSUE TITLE
Good Job!!!

### ISSUE THREAD

**Issue by ksong0xd** [Gteditor99/Nzen2-DDoSpy#1]
https://github.com/Gteditor99/Nzen2-DDoSpy/blob/412ac82982259c4eb851d7022d3524f053c1f8e0/DDoS.py#L1

Good job!! Gteditor99! But one thing you need to be aware of is the "subprocess.run" method is waiting for your batch file execution to finish.  so you are sending 65KB packets per xx seconds which are actually a smaller packet size to give network stress (you need to send them at once by using a different methodology like asynchronous)

Plus, you don't need to write the same batch files to achieve your goal. Because your ```subprocess.run()``` will run the batch file in your CPU's another logical process which means you will have the same result even if you use the same file on your while loop like this, which also means you don't have to write the repetitive code up there.

```python
 while True:
        subprocess.run('bot.bat') 
```

```subprocess.run()``` will make another process every time to run your batch file.
But as I said before, the subprocess is not asynchronous. so you may need to use another approach for async like https://docs.python.org/3/library/asyncio-subprocess.html#asyncio.create_subprocess_exec

Overall this project is exciting but. Few things I'd like to advise you in general are...

1. have a clear goal for this project.
2. have a clear test plan to make sure your thought is actually running on your computer as you originally plan (in the case of this project, maybe Virtual Machine to run against? or unit test?)
3. this is a great job as your first project to the world! But if it's more things to make the world a better place by your skill, you will earn more credit and be more famous!

**Comment by Gteditor99** [comment]
Thanks for the feedback 😄
